# Generated by Django 2.2 on 2020-03-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20200317_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='year',
            new_name='year_of_admission',
        ),
    ]
