# Generated by Django 2.2 on 2020-03-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20200317_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registered_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
