# Generated by Django 2.2 on 2020-03-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auto_20200317_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('100', '100 L'), ('200', '200 L'), ('300', '300 L'), ('400', '400 L'), ('500', '500 L')], default=100, max_length=2),
        ),
    ]
