# Generated by Django 2.2 on 2020-03-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_auto_20200317_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_levels',
        ),
    ]
