# Generated by Django 2.2 on 2020-03-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_auto_20200317_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('100', '100 L'), ('200', '200 L'), ('300', '300 L'), ('400', '400 L'), ('500', '500 L')], max_length=5),
        ),
    ]
