# Generated by Django 2.2 on 2020-03-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_auto_20200317_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-registered_date']},
        ),
    ]
