# Generated by Django 2.2 on 2020-03-18 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_auto_20200318_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('returning_date', models.DateTimeField()),
                ('borrowed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Student')),
            ],
        ),
    ]
