# Generated by Django 2.2 on 2020-03-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-issued_date']},
        ),
    ]
