# Generated by Django 2.2 on 2020-04-09 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_auto_20200409_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 23, 6, 40, 0, 709247), null=True),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
