# Generated by Django 2.2 on 2020-04-22 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_auto_20200422_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 6, 21, 50, 59, 706299), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 21, 50, 59, 706298)),
        ),
        migrations.AlterField(
            model_name='staff_book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 13, 21, 50, 59, 706299), null=True),
        ),
        migrations.AlterField(
            model_name='staff_book',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 21, 50, 59, 706298)),
        ),
    ]
