# Generated by Django 2.2 on 2020-04-09 05:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_auto_20200409_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 23, 6, 41, 15, 347679), null=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=15, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(choices=[('100', '100 L'), ('200', '200 L'), ('300', '300 L'), ('400', '400 L'), ('500', '500 L')], max_length=5)),
                ('year_of_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.Year_Of_Reg')),
            ],
            options={
                'verbose_name_plural': 'students',
                'ordering': ['registration_date'],
            },
        ),
    ]
