# Generated by Django 2.2 on 2020-04-27 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_auto_20200427_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 11, 21, 36, 45, 775268), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 21, 36, 45, 775267)),
        ),
        migrations.AlterField(
            model_name='staff_book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 18, 21, 36, 45, 775268), null=True),
        ),
        migrations.AlterField(
            model_name='staff_book',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 21, 36, 45, 775267)),
        ),
    ]
