# Generated by Django 2.2 on 2020-04-09 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_auto_20200409_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 23, 6, 44, 35, 649917), null=True),
        ),
    ]
