# Generated by Django 2.2 on 2020-04-27 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_auto_20200427_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 11, 22, 6, 19, 369179), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 22, 6, 19, 369178)),
        ),
        migrations.AlterField(
            model_name='staff_book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 18, 22, 6, 19, 369179), null=True),
        ),
        migrations.AlterField(
            model_name='staff_book',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 22, 6, 19, 369178)),
        ),
    ]
