# Generated by Django 2.2 on 2020-04-13 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_auto_20200413_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 27, 14, 41, 37, 727621), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='issued_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staff_book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 27, 14, 41, 37, 727621), null=True),
        ),
    ]
