# Generated by Django 2.2 on 2020-04-09 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_auto_20200409_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 23, 6, 54, 32, 58608), null=True),
        ),
    ]
