# Generated by Django 2.2 on 2020-04-19 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_auto_20200418_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-registration_date'], 'verbose_name_plural': 'staffs'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-registration_date'], 'verbose_name_plural': 'students'},
        ),
        migrations.AlterField(
            model_name='book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 3, 7, 52, 24, 564636), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 7, 52, 24, 564635)),
        ),
        migrations.AlterField(
            model_name='staff_book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 10, 7, 52, 24, 564636), null=True),
        ),
    ]
