# Generated by Django 2.2 on 2020-04-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0011_auto_20200401_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-registration_date'], 'verbose_name_plural': 'students'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='registered_date',
            new_name='registration_date',
        ),
    ]
