# Generated by Django 2.2 on 2020-04-19 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_auto_20200419_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-issued_date']},
        ),
        migrations.AlterModelOptions(
            name='staff_book',
            options={'ordering': ['-issued_date']},
        ),
        migrations.AlterField(
            model_name='book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 3, 16, 58, 47, 503344), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 16, 58, 47, 503343)),
        ),
        migrations.AlterField(
            model_name='staff_book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 10, 16, 58, 47, 518971), null=True),
        ),
        migrations.AlterField(
            model_name='staff_book',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 16, 58, 47, 518970)),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
