# Generated by Django 2.2 on 2020-04-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_auto_20200402_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['registration_date'], 'verbose_name_plural': 'students'},
        ),
    ]
