# Generated by Django 2.2 on 2020-04-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_auto_20200402_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rem_days',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
