# Generated by Django 2.2 on 2020-04-09 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_auto_20200409_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 23, 7, 31, 53, 654855), null=True),
        ),
    ]
