# Generated by Django 2.2 on 2020-04-19 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_auto_20200419_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 3, 17, 16, 27, 445886), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 17, 16, 27, 445885)),
        ),
        migrations.AlterField(
            model_name='staff_book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 10, 17, 16, 27, 445886), null=True),
        ),
        migrations.AlterField(
            model_name='staff_book',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 17, 16, 27, 445885)),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
