# Generated by Django 2.2 on 2020-04-19 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_auto_20200419_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 3, 17, 20, 34, 127104), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 17, 20, 34, 127103)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='staff_book',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 10, 17, 20, 34, 127104), null=True),
        ),
        migrations.AlterField(
            model_name='staff_book',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 17, 20, 34, 127103)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
