# Generated by Django 2.2 on 2020-04-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_auto_20200403_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rem_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
