# Generated by Django 2.2 on 2020-04-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0016_auto_20200403_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_days',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
