# Generated by Django 2.2 on 2020-04-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0018_auto_20200404_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_days',
            field=models.DateField(blank=True, null=True),
        ),
    ]
