# Generated by Django 2.2 on 2020-04-04 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0020_auto_20200404_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sample_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 13, 44, 43, 184576)),
        ),
    ]
