# Generated by Django 2.2 on 2020-04-04 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0021_book_sample_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sample_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 4, 13, 46, 43, 20617)),
        ),
    ]
