# Generated by Django 2.2 on 2020-04-04 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0022_auto_20200404_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sample_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 13, 48, 18, 471070)),
        ),
    ]
