# Generated by Django 2.2 on 2020-04-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0023_auto_20200404_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sample_date',
        ),
    ]
