# Generated by Django 2.2 on 2020-04-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0024_remove_book_sample_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_days',
            field=models.DateField(blank=True, null=True),
        ),
    ]
